databases:
  - name: Dalel
    ipAllowList: []
    databaseName: dalel
    user: dalel_user
services:
  - type: web
    name: dalel
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
